// packages/ui/react/src/components/atoms/ButtonLink/BTButtonLink.tsx
/**
 * BTButtonLink — inline hyperlink-style action atom.
 * Figma source: node 480:3197.
 *
 * @example
 * ```tsx
 * // Primary (default)
 * <BTButtonLink label="View details" onClick={goToDetails} />
 *
 * // With left icon
 * <BTButtonLink
 *   label="Cancel"
 *   variant="secondary"
 *   leftIcon={<CloseIcon />}
 *   disabled={loading}
 *   onClick={handleCancel}
 * />
 *
 * // Invert — for dark surfaces
 * <BTButtonLink label="Learn more" variant="invert" onClick={openUrl} />
 * ```
 */
import './BTButtonLink.css';
import type { BTButtonLinkProps } from './BTButtonLink.types';

export function BTButtonLink({
  label,
  variant = 'primary',
  leftIcon,
  rightIcon,
  disabled,
  className,
  ...rest
}: BTButtonLinkProps) {
  return (
    <button
      type="button"
      className={[
        'bt-button-link',
        `bt-button-link--${variant}`,
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      disabled={disabled}
      data-testid="bt-button-link"
      {...rest}
    >
      {leftIcon}
      <span className="bt-button-link__label">{label}</span>
      {rightIcon}
    </button>
  );
}

BTButtonLink.displayName = 'BTButtonLink';

// packages/ui/vue/src/components/atoms/ButtonLink/BTButtonLink.vue
<!--
  BTButtonLink — inline hyperlink-style action atom.
  Figma source: node 480:3197.

  Usage:
  ```vue
  <BTButtonLink label="View details" @click="goToDetails" />

  <BTButtonLink
    label="Cancel"
    variant="secondary"
    :disabled="loading"
    @click="handleCancel"
  >
    <template #left-icon><IconClose :size="16" /></template>
  </BTButtonLink>

  <BTButtonLink label="Learn more" variant="invert" @click="openUrl" />
  ```
-->
<script setup lang="ts">
import './BTButtonLink.css';
import type { BTButtonLinkProps } from './BTButtonLink.types';

const props = withDefaults(defineProps<BTButtonLinkProps>(), {
  variant: 'primary',
  disabled: false,
});

const emit = defineEmits<{ click: [] }>();

const onClick = () => {
  if (!props.disabled) emit('click');
};
</script>

<template>
  <button
    class="bt-button-link"
    :class="`bt-button-link--${variant}`"
    :disabled="disabled"
    type="button"
    data-testid="bt-button-link"
    @click="onClick"
  >
    <slot name="left-icon" />
    <span class="bt-button-link__label">{{ label }}</span>
    <slot name="right-icon" />
  </button>
</template>
