// packages/ui/react/src/components/atoms/Badge/BTBadge.tsx
/**
 * BTBadge — status label atom.
 * Sliced from Figma `Badge` (node 72:1516). Mirrors @btech/ui-vue BTBadge
 * one-to-one (same prop names, same variant logic, same render priority).
 *
 * ## Usage:
 * ```tsx
 * // Normal
 * <BTBadge label="Approved" variant="success" />
 *
 * // With left icon
 * <BTBadge label="Waiting" variant="waiting" leftIcon={<ClockIcon size={16} />} />
 *
 * // Reverse (solid bg + white text)
 * <BTBadge label="Rejected" variant="reject" reverseColors />
 * ```
 */
import * as React from 'react';
import type { BTBadgeProps } from './BTBadge.types.js';
import './BTBadge.css';

/**
 * Status label pill. See file header for usage examples.
 */
export const BTBadge = React.forwardRef<HTMLSpanElement, BTBadgeProps>(
  (
    {
      label = 'Badge',
      variant = 'success',
      reverseColors = false,
      leftIcon,
      rightIcon,
      className,
      ...rest
    },
    ref,
  ) => {
    const classes = [
      'bt-badge',
      `bt-badge--${variant}`,
      reverseColors ? 'bt-badge--reverse' : '',
      className ?? '',
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <span ref={ref} className={classes} data-testid="bt-badge" {...rest}>
        {leftIcon}
        <span className="bt-badge__label">{label}</span>
        {rightIcon}
      </span>
    );
  },
);

BTBadge.displayName = 'BTBadge';

// packages/ui/vue/src/components/atoms/Badge/BTBadge.vue
<!-- BTBadge — status label atom.
     Figma source: node 72:1516.
     All visual values come from Figma. Reference repo (buma-ui Vue) used for
     code pattern (withDefaults, script setup, named slots) only.
-->
<script setup lang="ts">
import { computed } from 'vue';
import './BTBadge.css';
import type { BTBadgeProps } from './BTBadge.types';

const props = withDefaults(defineProps<BTBadgeProps>(), {
  label: 'Badge',
  variant: 'success',
  reverseColors: false,
});

const badgeClass = computed(() =>
  [
    'bt-badge',
    `bt-badge--${props.variant}`,
    props.reverseColors ? 'bt-badge--reverse' : '',
  ]
    .filter(Boolean)
    .join(' '),
);
</script>

<template>
  <span :class="badgeClass" data-testid="bt-badge">
    <slot name="leftIcon" />
    <span class="bt-badge__label">{{ label }}</span>
    <slot name="rightIcon" />
  </span>
</template>
