// packages/ui/react/src/components/atoms/Checkbox/BTCheckbox.tsx
/**
 * BTCheckbox — Figma 504:4181
 *
 * @example
 * ```tsx
 * // Basic controlled checkbox
 * const [checked, setChecked] = useState(false);
 * <BTCheckbox checked={checked} onChange={setChecked} label="I agree" />
 *
 * // Indeterminate / error / disabled
 * <BTCheckbox checked={false} indeterminate onChange={onChange} label="Select all" />
 * <BTCheckbox checked={false} error onChange={onChange} subtext="Required field" />
 * <BTCheckbox checked={false} disabled label="Unavailable" />
 * ```
 */
import { useRef, useEffect, useCallback } from 'react';
import './BTCheckbox.css';
import type { BTCheckboxProps } from './BTCheckbox.types';

export function BTCheckbox({
  checked = false,
  indeterminate = false,
  disabled = false,
  error = false,
  label,
  subtext,
  onChange,
  className,
}: BTCheckboxProps) {
  const inputRef = useRef<HTMLInputElement>(null);

  // The indeterminate state is a DOM property, not an HTML attribute.
  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.indeterminate = indeterminate;
    }
  }, [indeterminate]);

  const handleChange = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      onChange?.(event.target.checked);
    },
    [onChange],
  );

  const rootClass = [
    'bt-checkbox',
    disabled ? 'bt-checkbox--disabled' : '',
    error && !disabled ? 'bt-checkbox--error' : '',
    className ?? '',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <label className={rootClass}>
      <span className="bt-checkbox__control">
        <input
          ref={inputRef}
          type="checkbox"
          className="bt-checkbox__input"
          checked={checked}
          disabled={disabled}
          onChange={handleChange}
        />
        <span className="bt-checkbox__box" aria-hidden />
      </span>

      {(label || subtext) && (
        <span className="bt-checkbox__text">
          {label && <span className="bt-checkbox__label">{label}</span>}
          {subtext && <span className="bt-checkbox__subtext">{subtext}</span>}
        </span>
      )}
    </label>
  );
}

BTCheckbox.displayName = 'BTCheckbox';

// packages/ui/vue/src/components/atoms/Checkbox/BTCheckbox.vue
<script setup lang="ts">
/**
 * BTCheckbox — Figma 504:4181
 *
 * @example
 * ```vue
 * <!-- Basic controlled checkbox -->
 * <BTCheckbox v-model="accepted" label="I agree" />
 *
 * <!-- Indeterminate / error / disabled -->
 * <BTCheckbox v-model="partial" :indeterminate="true" label="Select all" />
 * <BTCheckbox v-model="value" :error="true" subtext="Required field" />
 * <BTCheckbox v-model="value" :disabled="true" label="Unavailable" />
 * ```
 */
import { ref, watch, onMounted } from 'vue';
import './BTCheckbox.css';
import type { BTCheckboxProps } from './BTCheckbox.types';

const props = withDefaults(defineProps<BTCheckboxProps>(), {
  modelValue: false,
  indeterminate: false,
  disabled: false,
  error: false,
});

const emit = defineEmits<{
  'update:modelValue': [value: boolean];
}>();

const inputRef = ref<HTMLInputElement | null>(null);

// Sync the non-attribute indeterminate property via DOM ref.
function syncIndeterminate() {
  if (inputRef.value) {
    inputRef.value.indeterminate = props.indeterminate;
  }
}

onMounted(syncIndeterminate);
watch(() => props.indeterminate, syncIndeterminate);

function onChange(event: Event) {
  if (props.disabled) return;
  emit('update:modelValue', (event.target as HTMLInputElement).checked);
}
</script>

<template>
  <label
    class="bt-checkbox"
    :class="{
      'bt-checkbox--disabled': disabled,
      'bt-checkbox--error': error && !disabled,
    }"
  >
    <span class="bt-checkbox__control">
      <input
        ref="inputRef"
        type="checkbox"
        class="bt-checkbox__input"
        :checked="modelValue"
        :disabled="disabled"
        @change="onChange"
      />
      <span class="bt-checkbox__box" aria-hidden="true" />
    </span>

    <span v-if="label || subtext" class="bt-checkbox__text">
      <span v-if="label" class="bt-checkbox__label">{{ label }}</span>
      <span v-if="subtext" class="bt-checkbox__subtext">{{ subtext }}</span>
    </span>
  </label>
</template>
