// packages/ui/vue/src/components/molecules/TooltipStep/BTTooltipStep.vue
<script setup lang="ts">
/**
 * BTTooltipStep — coachmark / pagination-step balloon.
 *
 * Figma: https://www.figma.com/design/WANr9drWYNYbMPuT2sMeHi/?node-id=478-2463
 *
 * A standalone tooltip card used for onboarding coach marks. The component
 * renders the balloon shell (arrow + body); positioning relative to the
 * target element is the responsibility of the parent.
 *
 * @example
 * ```vue
 * <!-- Step 1 of 3 — base button variant -->
 * <BTTooltipStep
 *   label="Fitur Baru"
 *   description="Klik tombol ini untuk memulai."
 *   step-label="Step 1 of 3"
 *   step-variant="button"
 *   has-close
 *   prev-label="Kembali"
 *   next-label="Selanjutnya"
 *   position="bottom"
 *   @prev="goPrev"
 *   @next="goNext"
 *   @close="endTour"
 * />
 * ```
 */
import { computed } from 'vue';
import type {
  BTTooltipStepVariant,
  BTTooltipStepPosition,
  BTTooltipStepArrowPosition,
} from './BTTooltipStep.types';
import './BTTooltipStep.css';

const props = withDefaults(
  defineProps<{
    label?: string;
    description: string;
    stepLabel?: string;
    stepVariant?: BTTooltipStepVariant;
    hasClose?: boolean;
    prevLabel?: string;
    nextLabel?: string;
    position?: BTTooltipStepPosition;
    arrowPosition?: BTTooltipStepArrowPosition;
    /**
     * Optional dynamic arrow offset (e.g. "120px") — overrides the
     * arrowPosition enum when provided.  Used by coachmark overlays that
     * compute the exact trigger-centre distance after viewport clamping.
     */
    arrowOffset?: string;
  }>(),
  {
    stepVariant: 'button',
    hasClose: false,
    prevLabel: 'Prev',
    nextLabel: 'Next',
    position: 'top',
    arrowPosition: 'mid',
  },
);

const emit = defineEmits<{
  (e: 'prev'): void;
  (e: 'next'): void;
  (e: 'close'): void;
}>();

// ── Computed ────────────────────────────────────────────────────────────────

const isHorizontalPosition = computed(
  () => props.position === 'left' || props.position === 'right',
);

const hasFooter = computed(
  () => !!props.stepLabel || props.stepVariant !== undefined,
);

const hasHeader = computed(() => !!props.label || props.hasClose);

/** SVG path for the caret arrow, pointing toward the target (away from body). */
const arrowPath = computed<string>(() => {
  switch (props.position) {
    case 'bottom':
      return 'M0 8 L7 1 Q8 0 9 1 L16 8 Z'; // ▲ top of balloon → trigger below
    case 'left':
      return 'M0 0 L7 7 Q8 8 7 9 L0 16 Z';  // ▶ right of balloon → trigger left
    case 'right':
      return 'M8 0 L1 7 Q0 8 1 9 L8 16 Z';  // ◀ left of balloon → trigger right
    case 'top':
    default:
      return 'M0 0 L7 7 Q8 8 9 7 L16 0 Z';  // ▼ bottom of balloon → trigger above
  }
});

const arrowViewBox = computed<string>(() =>
  isHorizontalPosition.value ? '0 0 8 16' : '0 0 16 8',
);
const arrowWidth = computed<number>(() => (isHorizontalPosition.value ? 8 : 16));
const arrowHeight = computed<number>(() => (isHorizontalPosition.value ? 16 : 8));

const outerClass = computed(() => [
  'bt-tooltip-step',
  `bt-tooltip-step--${props.position}`,
]);

const arrowRowClass = computed(() =>
  `bt-tooltip-step__arrow-row bt-tooltip-step__arrow-row--${props.arrowPosition}`,
);

const arrowColClass = computed(() =>
  `bt-tooltip-step__arrow-col bt-tooltip-step__arrow-col--${props.arrowPosition}`,
);

const footerClass = computed(() => [
  'bt-tooltip-step__footer',
  props.stepVariant === 'centered' ? 'bt-tooltip-step__footer--centered' : '',
]);
</script>

<template>
  <div :class="outerClass" role="dialog" aria-modal="false">
    <!-- Arrow (horizontal: row wrapper; vertical: col wrapper).
         arrowOffset prop sets --bt-arrow-offset inline (beats the class-based
         enum default), enabling pixel-accurate arrow pointing in overlays. -->
    <template v-if="!isHorizontalPosition">
      <div
        :class="arrowRowClass"
        :style="arrowOffset ? { '--bt-arrow-offset': arrowOffset } : undefined"
      >
        <svg
          class="bt-tooltip-step__arrow"
          :width="arrowWidth"
          :height="arrowHeight"
          :viewBox="arrowViewBox"
          fill="none"
          aria-hidden="true"
        >
          <path :d="arrowPath" fill="var(--bg-inverse)" />
        </svg>
      </div>
    </template>
    <template v-else>
      <div
        :class="arrowColClass"
        :style="arrowOffset ? { '--bt-arrow-offset': arrowOffset } : undefined"
      >
        <svg
          class="bt-tooltip-step__arrow"
          :width="arrowWidth"
          :height="arrowHeight"
          :viewBox="arrowViewBox"
          fill="none"
          aria-hidden="true"
        >
          <path :d="arrowPath" fill="var(--bg-inverse)" />
        </svg>
      </div>
    </template>

    <!-- Body card -->
    <div class="bt-tooltip-step__body">
      <!-- Header: label + optional close button -->
      <div v-if="hasHeader" class="bt-tooltip-step__header">
        <p v-if="label" class="bt-tooltip-step__label">{{ label }}</p>
        <div v-if="!label && hasClose" style="flex: 1" />
        <button
          v-if="hasClose"
          class="bt-tooltip-step__close"
          type="button"
          aria-label="Tutup"
          @click="emit('close')"
        >
          <!-- Close × icon -->
          <svg viewBox="0 0 18 18" fill="none" aria-hidden="true">
            <path
              d="M14 4L4 14M4 4l10 10"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
            />
          </svg>
        </button>
      </div>

      <!-- Description -->
      <p class="bt-tooltip-step__description">{{ description }}</p>

      <!-- Optional rich content slot -->
      <slot />

      <!-- Footer: step label + navigation buttons -->
      <div v-if="hasFooter" :class="footerClass">
        <!-- ── variant: button (default) ── -->
        <template v-if="stepVariant === 'button'">
          <p v-if="stepLabel" class="bt-tooltip-step__step-label">{{ stepLabel }}</p>
          <div style="display: flex; gap: 8px; flex-shrink: 0">
            <button
              class="bt-tooltip-step__btn"
              type="button"
              @click="emit('prev')"
            >
              {{ prevLabel }}
            </button>
            <button
              class="bt-tooltip-step__btn"
              type="button"
              @click="emit('next')"
            >
              {{ nextLabel }}
            </button>
          </div>
        </template>

        <!-- ── variant: link ── -->
        <template v-else-if="stepVariant === 'link'">
          <p v-if="stepLabel" class="bt-tooltip-step__step-label">{{ stepLabel }}</p>
          <div style="display: flex; gap: 12px; flex-shrink: 0">
            <button
              class="bt-tooltip-step__btn-link bt-tooltip-step__btn-link--prev"
              type="button"
              @click="emit('prev')"
            >
              {{ prevLabel }}
            </button>
            <button
              class="bt-tooltip-step__btn-link bt-tooltip-step__btn-link--next"
              type="button"
              @click="emit('next')"
            >
              {{ nextLabel }}
            </button>
          </div>
        </template>

        <!-- ── variant: centered ── -->
        <template v-else-if="stepVariant === 'centered'">
          <!-- Prev icon button -->
          <button
            class="bt-tooltip-step__btn-icon"
            type="button"
            aria-label="Sebelumnya"
            @click="emit('prev')"
          >
            <svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
              <path
                d="M10 12L6 8l4-4"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          </button>

          <p v-if="stepLabel" class="bt-tooltip-step__step-label">{{ stepLabel }}</p>

          <!-- Next icon button -->
          <button
            class="bt-tooltip-step__btn-icon"
            type="button"
            aria-label="Selanjutnya"
            @click="emit('next')"
          >
            <svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
              <path
                d="M6 12l4-4-4-4"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          </button>
        </template>
      </div>
    </div>
  </div>
</template>

// packages/ui/react/src/components/molecules/TooltipStep/BTTooltipStep.tsx
/**
 * BTTooltipStep — coachmark / pagination-step balloon.
 *
 * Figma: https://www.figma.com/design/WANr9drWYNYbMPuT2sMeHi/?node-id=478-2463
 *
 * @example
 * ```tsx
 * <BTTooltipStep
 *   label="Fitur Baru"
 *   description="Klik tombol ini untuk memulai."
 *   stepLabel="Step 1 of 3"
 *   stepVariant="button"
 *   hasClose
 *   prevLabel="Kembali"
 *   nextLabel="Selanjutnya"
 *   position="bottom"
 *   onPrev={goPrev}
 *   onNext={goNext}
 *   onClose={endTour}
 * />
 * ```
 */
import { type ReactNode, type CSSProperties } from 'react';
import type {
  BTTooltipStepVariant,
  BTTooltipStepPosition,
  BTTooltipStepArrowPosition,
} from './BTTooltipStep.types';
import './BTTooltipStep.css';

export interface BTTooltipStepReactProps {
  label?: string;
  description: string;
  stepLabel?: string;
  stepVariant?: BTTooltipStepVariant;
  hasClose?: boolean;
  prevLabel?: string;
  nextLabel?: string;
  position?: BTTooltipStepPosition;
  arrowPosition?: BTTooltipStepArrowPosition;
  /**
   * Optional dynamic arrow offset (e.g. "120px") — overrides the
   * arrowPosition enum when provided.  Used by coachmark overlays that
   * compute the exact trigger-centre distance after viewport clamping.
   */
  arrowOffset?: string;
  /** Rich content rendered between description and footer. */
  children?: ReactNode;
  onPrev?: () => void;
  onNext?: () => void;
  onClose?: () => void;
}

function getArrowPath(position: BTTooltipStepPosition): string {
  switch (position) {
    case 'bottom': return 'M0 8 L7 1 Q8 0 9 1 L16 8 Z';
    case 'left':   return 'M0 0 L7 7 Q8 8 7 9 L0 16 Z';
    case 'right':  return 'M8 0 L1 7 Q0 8 1 9 L8 16 Z';
    case 'top':
    default:       return 'M0 0 L7 7 Q8 8 9 7 L16 0 Z';
  }
}

export function BTTooltipStep({
  label,
  description,
  stepLabel,
  stepVariant = 'button',
  hasClose = false,
  prevLabel = 'Prev',
  nextLabel = 'Next',
  position = 'top',
  arrowPosition = 'mid',
  arrowOffset,
  children,
  onPrev,
  onNext,
  onClose,
}: BTTooltipStepReactProps) {
  const isHorizontal = position === 'left' || position === 'right';
  const arrowPath = getArrowPath(position);
  const arrowViewBox = isHorizontal ? '0 0 8 16' : '0 0 16 8';
  const arrowW = isHorizontal ? 8 : 16;
  const arrowH = isHorizontal ? 16 : 8;
  const hasHeader = !!(label || hasClose);
  const hasFooter = !!(stepLabel || stepVariant);

  const arrowSvg = (
    <svg className="bt-tooltip-step__arrow" width={arrowW} height={arrowH} viewBox={arrowViewBox} fill="none" aria-hidden="true">
      <path d={arrowPath} fill="var(--bg-inverse)" />
    </svg>
  );

  const arrowRowClass = `bt-tooltip-step__arrow-row bt-tooltip-step__arrow-row--${arrowPosition}`;
  const arrowColClass = `bt-tooltip-step__arrow-col bt-tooltip-step__arrow-col--${arrowPosition}`;

  return (
    <div
      className={`bt-tooltip-step bt-tooltip-step--${position}`}
      role="dialog"
      aria-modal={false}
    >
      {/* Arrow — arrowOffset prop overrides enum-based --bt-arrow-offset */}
      {!isHorizontal ? (
        <div
          className={arrowRowClass}
          style={arrowOffset ? { '--bt-arrow-offset': arrowOffset } as CSSProperties : undefined}
        >
          {arrowSvg}
        </div>
      ) : (
        <div
          className={arrowColClass}
          style={arrowOffset ? { '--bt-arrow-offset': arrowOffset } as CSSProperties : undefined}
        >
          {arrowSvg}
        </div>
      )}

      {/* Body card */}
      <div className="bt-tooltip-step__body">
        {/* Header */}
        {hasHeader && (
          <div className="bt-tooltip-step__header">
            {label && <p className="bt-tooltip-step__label">{label}</p>}
            {!label && hasClose && <div style={{ flex: 1 }} />}
            {hasClose && (
              <button
                className="bt-tooltip-step__close"
                type="button"
                aria-label="Tutup"
                onClick={onClose}
              >
                <svg viewBox="0 0 18 18" fill="none" aria-hidden="true">
                  <path
                    d="M14 4L4 14M4 4l10 10"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                  />
                </svg>
              </button>
            )}
          </div>
        )}

        {/* Description */}
        <p className="bt-tooltip-step__description">{description}</p>

        {/* Rich content slot */}
        {children}

        {/* Footer */}
        {hasFooter && (
          <div
            className={`bt-tooltip-step__footer${
              stepVariant === 'centered' ? ' bt-tooltip-step__footer--centered' : ''
            }`}
          >
            {/* ── button variant ── */}
            {stepVariant === 'button' && (
              <>
                {stepLabel && (
                  <p className="bt-tooltip-step__step-label">{stepLabel}</p>
                )}
                <div style={{ display: 'flex', gap: 8, flexShrink: 0 }}>
                  <button className="bt-tooltip-step__btn" type="button" onClick={onPrev}>
                    {prevLabel}
                  </button>
                  <button className="bt-tooltip-step__btn" type="button" onClick={onNext}>
                    {nextLabel}
                  </button>
                </div>
              </>
            )}

            {/* ── link variant ── */}
            {stepVariant === 'link' && (
              <>
                {stepLabel && (
                  <p className="bt-tooltip-step__step-label">{stepLabel}</p>
                )}
                <div style={{ display: 'flex', gap: 12, flexShrink: 0 }}>
                  <button
                    className="bt-tooltip-step__btn-link bt-tooltip-step__btn-link--prev"
                    type="button"
                    onClick={onPrev}
                  >
                    {prevLabel}
                  </button>
                  <button
                    className="bt-tooltip-step__btn-link bt-tooltip-step__btn-link--next"
                    type="button"
                    onClick={onNext}
                  >
                    {nextLabel}
                  </button>
                </div>
              </>
            )}

            {/* ── centered variant ── */}
            {stepVariant === 'centered' && (
              <>
                <button
                  className="bt-tooltip-step__btn-icon"
                  type="button"
                  aria-label="Sebelumnya"
                  onClick={onPrev}
                >
                  <svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
                    <path
                      d="M10 12L6 8l4-4"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </button>
                {stepLabel && (
                  <p className="bt-tooltip-step__step-label">{stepLabel}</p>
                )}
                <button
                  className="bt-tooltip-step__btn-icon"
                  type="button"
                  aria-label="Selanjutnya"
                  onClick={onNext}
                >
                  <svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
                    <path
                      d="M6 12l4-4-4-4"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </button>
              </>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
