// packages/ui/vue/src/components/molecules/Tabs/BTTabs.vue
<!-- BTTabs — tab molecule (Figma 1:53 / Base/TabItem 434:5262).
 *
 * Two variants: 'segmented' (pill tray) · 'line' (underline).
 *
 * Example:
 * ```vue
 * <script setup lang="ts">
 * import { ref } from 'vue';
 * import { BTTabs } from '@btech/ui-vue';
 * const active = ref(0);
 * </script>
 * <template>
 *   <BTTabs
 *     variant="segmented"
 *     :tabs="[{ label: 'Overview' }, { label: 'Details' }, { label: 'History' }]"
 *     v-model:activeIndex="active"
 *   />
 *   <BTTabs
 *     variant="line"
 *     :tabs="[{ label: 'Overview' }, { label: 'Details' }]"
 *     v-model:activeIndex="active"
 *   />
 * </template>
 * ```
-->
<script setup lang="ts">
import './BTTabs.css';
import { computed } from 'vue';
import type { BTTabsProps } from './BTTabs.types';

const props = withDefaults(defineProps<BTTabsProps>(), {
  variant: 'segmented',
  activeIndex: 0,
});

const emit = defineEmits<{
  (e: 'update:activeIndex', index: number): void;
}>();

const currentIndex = computed(() => props.activeIndex ?? 0);

function select(index: number, disabled?: boolean) {
  if (disabled) return;
  emit('update:activeIndex', index);
}

const rootClass = computed(() => [
  'bt-tabs',
  `bt-tabs--${props.variant}`,
  props.className,
]);
</script>

<template>
  <div :class="rootClass" role="tablist">
    <button
      v-for="(tab, i) in tabs"
      :key="i"
      role="tab"
      :class="[
        'bt-tabs__item',
        i === currentIndex && 'bt-tabs__item--active',
      ]"
      :aria-selected="i === currentIndex"
      :aria-disabled="tab.disabled || undefined"
      :disabled="tab.disabled"
      :tabindex="i === currentIndex ? 0 : -1"
      @click="select(i, tab.disabled)"
    >
      <!-- Optional leading icon via scoped slot -->
      <span v-if="$slots[`leading-icon-${i}`]" class="bt-tabs__icon">
        <slot :name="`leading-icon-${i}`" />
      </span>

      {{ tab.label }}

      <!-- Optional trailing icon via scoped slot -->
      <span v-if="$slots[`trailing-icon-${i}`]" class="bt-tabs__icon">
        <slot :name="`trailing-icon-${i}`" />
      </span>
    </button>
  </div>
</template>

// packages/ui/react/src/components/molecules/Tabs/BTTabs.tsx
/**
 * BTTabs — tab molecule (Figma 1:53 / Base/TabItem 434:5262).
 *
 * Two variants: 'segmented' (pill tray) · 'line' (underline).
 *
 * @example
 * ```tsx
 * const [active, setActive] = useState(0);
 *
 * // Segmented
 * <BTTabs
 *   variant="segmented"
 *   tabs={[{ label: 'Overview' }, { label: 'Details' }, { label: 'History' }]}
 *   activeIndex={active}
 *   onActiveIndexChange={setActive}
 * />
 *
 * // Line
 * <BTTabs
 *   variant="line"
 *   tabs={[{ label: 'Overview' }, { label: 'Details' }]}
 *   activeIndex={active}
 *   onActiveIndexChange={setActive}
 * />
 * ```
 */
import { useCallback } from 'react';
import './BTTabs.css';
import type { BTTabsProps } from './BTTabs.types';

export interface BTTabsReactProps extends BTTabsProps {
  /** Called when the user selects a tab. Receives the new active index. */
  onActiveIndexChange?: (index: number) => void;
  /** Leading icon per tab index (render prop). */
  leadingIcon?: (index: number) => React.ReactNode;
  /** Trailing icon per tab index (render prop). */
  trailingIcon?: (index: number) => React.ReactNode;
}

export function BTTabs({
  variant = 'segmented',
  tabs,
  activeIndex = 0,
  onActiveIndexChange,
  leadingIcon,
  trailingIcon,
  className,
}: BTTabsReactProps) {
  const handleClick = useCallback(
    (index: number, disabled?: boolean) => {
      if (disabled) return;
      onActiveIndexChange?.(index);
    },
    [onActiveIndexChange],
  );

  const rootClass = [
    'bt-tabs',
    `bt-tabs--${variant}`,
    className ?? '',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={rootClass} role="tablist">
      {tabs.map((tab, i) => (
        <button
          key={i}
          role="tab"
          className={[
            'bt-tabs__item',
            i === activeIndex ? 'bt-tabs__item--active' : '',
          ]
            .filter(Boolean)
            .join(' ')}
          aria-selected={i === activeIndex}
          aria-disabled={tab.disabled || undefined}
          disabled={tab.disabled}
          tabIndex={i === activeIndex ? 0 : -1}
          onClick={() => handleClick(i, tab.disabled)}
        >
          {leadingIcon && (
            <span className="bt-tabs__icon">{leadingIcon(i)}</span>
          )}
          {tab.label}
          {trailingIcon && (
            <span className="bt-tabs__icon">{trailingIcon(i)}</span>
          )}
        </button>
      ))}
    </div>
  );
}

BTTabs.displayName = 'BTTabs';
